export default {
  'admin.bankAccounts.tableAccountName': 'Name',
  'admin.bankAccounts.tableBankName': 'Bank',
  'admin.bankAccounts.tableEncryptedIban': 'IBAN',
  'admin.bankAccounts.tableStatus': 'Status',
  'admin.bankAccounts.holder': 'Holder',
  'admin.bankAccounts.bic': 'BIC',
  'admin.bankAccounts.iban': 'IBAN',
  'admin.bankAccounts.bankName': 'Bank name',
  'admin.bankAccounts.directDebit': 'Direct debit',
  'admin.bankAccounts.modalHeaderAdd': 'Create bank account',
  'admin.bankAccounts.headerBankAccounts': 'Bank accounts',
  'admin.bankAccounts.addNew': 'Create bank account',
  'admin.bankAccounts.tableHolder': 'Holder',
  'admin.bankAccounts.tableBic': 'BIC',
  'admin.bankAccounts.tableIban': 'IBAN',
  'admin.bankAccounts.tableDirectDebit': 'Direc Debit',
};
