export default {
  'admin.billings.titleDetails': 'Invoice',
  'admin.billings.customerName': 'Powertaker',
  'admin.billings.dateRange': 'Billing period',
  'admin.billings.customerEmail': 'Email',
  'admin.billings.status': 'Status',
  'admin.billings.titleReference': 'Consumption amount',
  'admin.billings.tableMeterSerial': 'Meter number',
  'admin.billings.tableDates': 'Dates',
  'admin.billings.tableBeginReadingKwh': 'Begin reading',
  'admin.billings.tableEndReadingKwh': 'End reading',
  'admin.billings.tableConsumedEnergyKwh': 'Consumed energy',
  'admin.billings.tableDesignation': 'Designation',
  'admin.billings.tableAmount': 'Amount',
  'admin.billings.tableUnit': 'Unit',
  'admin.billings.tablePriceForUnit': 'Unit price',
  'admin.billings.tableNetAmount': 'Net amount',
  'admin.billings.titleInvoices': 'Billing',
  'admin.billings.basePrice': 'Base price',
  'admin.billings.workingPrice': 'Working price',
  'admin.billings.tableInvoiceNumber': 'Invoice Num',
  'admin.billings.tableBeginDate': 'Begin Date',
  'admin.billings.tableEndDate': 'End Date',
  'admin.billings.tableStatus': 'Status',
  'admin.billings.addNew': 'Add new billing',
  'admin.billings.modalHeaderAdd': 'Add new billing',
  'admin.billings.beginDate': 'Begin Date',
  'admin.billings.endDate': 'End Date',
  'admin.billings.invoiceNumber': 'Invoice number',
  'admin.billings.open': 'open',
  'admin.billings.calculated': 'calculated',
  'admin.billings.delivered': 'delivered',
  'admin.billings.settled': 'settled',
  'admin.billings.closed': 'closed',
  'admin.billings.headerBillingItems': 'Billing Items',
};
