export default {
  'admin.billings.titleDetails': 'Invoice',
  'admin.billings.customerName': 'Powertaker',
  'admin.billings.dateRange': 'Billing period',
  'admin.billings.customerEmail': 'Email',
  'admin.billings.status': 'Status',
  'admin.billings.titleReference': 'Consumption amount',
  'admin.billings.tableMeterSerial': 'Meter number',
  'admin.billings.tableDates': 'Dates',
  'admin.billings.tableBeginReadingKwh': 'Begin reading',
  'admin.billings.tableEndReadingKwh': 'End reading',
  'admin.billings.tableConsumedEnergyKwh': 'Consumed energy',
  'admin.billings.tableDesignation': 'Designation',
  'admin.billings.tableAmount': 'Amount',
  'admin.billings.tableUnit': 'Unit',
  'admin.billings.tablePriceForUnit': 'Unit price',
  'admin.billings.tableNetAmount': 'Net amount',
  'admin.billings.titleInvoices': 'Billing',
  'admin.billings.basePrice': 'Base price',
  'admin.billings.workingPrice': 'Working price',
};
