export default {
  'admin.billingCycles.backBillingCycles': 'Billing cycles',
  'admin.billingCycles.addNew': 'New billing cycle',
  'admin.billingCycles.modalHeaderAdd': 'New billing cycle',
  'admin.billingCycles.tableName': 'Name',
  'admin.billingCycles.tableDates': 'Dates',
  'admin.billingCycles.maloListTitle': 'Market locations',
  'admin.billingCycles.barsLegendTitle': 'Legend',
  'admin.billingCycles.barsLegendClosed': 'Closed',
  'admin.billingCycles.barsLegendVoid': 'Void',
  'admin.billingCycles.barsLegendSettled': 'Settled',
  'admin.billingCycles.barsLegendDelivered': 'Delivered',
  'admin.billingCycles.barsLegendQueued': 'Queued',
  'admin.billingCycles.barsLegendDocumented': 'Documented',
  'admin.billingCycles.barsLegendCalculated': 'Calculated',
  'admin.billingCycles.barsLegendOpen': 'Open',
  'admin.billingCycles.barsLegendPT': 'Powertaker',
  'admin.billingCycles.barsLegendGAP': 'Gap',
  'admin.billingCycles.barsLegendTP': 'Third party',
};
