export default {
  'admin.contracts.register': 'Register',
  'admin.contracts.status': 'Status',
  'admin.contracts.forecastWattHour': 'Estimate',
  'admin.contracts.beginDate': 'Customer since',
  'admin.contracts.headerContractData': 'Contract Data',
  'admin.contracts.fullContractNumber': 'Contract number',
  'admin.contracts.endDate': 'End date',
  'admin.contracts.signingDate': 'Signed on',
  'admin.contracts.signingUser': 'Signed by',
  'admin.contracts.cancelationDate': 'Canceled on',
  'admin.contracts.headerBillingBasis': 'Billing basis',
  'admin.contracts.forecastWattHourPa': 'Estimated consumption',
  'admin.contracts.renewableEnergyLawTaxation': 'EEG calculation',
  'admin.contracts.thirdPartyBillingNumber': 'Invoice reference',
  'admin.contracts.thirdPartyRenterNumber': 'Tenant reference',
  'admin.contracts.headerSupplierChange': 'Supplier change',
  'admin.contracts.oldSupplierName': 'Prior supplier',
  'admin.contracts.oldCustomerNumber': 'Prior customer number',
  'admin.contracts.oldAccountNumber': 'Prior account number',
};
