export default {
  'admin.contracts.register': 'Register',
  'admin.contracts.status': 'Status',
  'admin.contracts.forecastWattHour': 'Estimate',
  'admin.contracts.beginDate': 'Customer since',
  'admin.contracts.headerContractData': 'Contract Data',
  'admin.contracts.fullContractNumber': 'Contract number',
  'admin.contracts.endDate': 'End date',
  'admin.contracts.signingDate': 'Signed on',
  'admin.contracts.signingUser': 'Signed by',
  'admin.contracts.cancelationDate': 'Canceled on',
  'admin.contracts.headerBillingBasis': 'Billing basis',
  'admin.contracts.forecastWattHourPa': 'Estimated consumption',
  'admin.contracts.renewableEnergyLawTaxation': 'EEG calculation',
  'admin.contracts.thirdPartyBillingNumber': 'Invoice reference',
  'admin.contracts.thirdPartyRenterNumber': 'Tenant reference',
  'admin.contracts.headerSupplierChange': 'Supplier change',
  'admin.contracts.oldSupplierName': 'Prior supplier',
  'admin.contracts.oldCustomerNumber': 'Prior customer number',
  'admin.contracts.oldAccountNumber': 'Prior account number',
  'admin.contracts.headerGroupContracts': 'Contracts',
  'admin.contracts.descriptionGroupContracts': 'List of all contracts for local group',
  'admin.contracts.tableType': 'Type',
  'admin.contracts.tableStatus': 'Status',
  'admin.contracts.tableSince': 'Begin',
  'admin.contracts.tableNumber': 'Contract #',
  'admin.contracts.tableName': 'Name',
  'admin.contracts.tableGroupName': 'Group name',
  'admin.contracts.tableRegisterName': 'Register name',
  'admin.contracts.tableContractNumber': 'Contract number',
  'admin.contracts.tableBeginDate': 'Start',
  'admin.contracts.tableEndDate': 'End',
  'admin.contracts.contract_metering_point_operator': 'Metering Point Operator',
  'admin.contracts.contract_localpool_processing': 'Local Pool Processing',
  'admin.contracts.contract_localpool_power_taker': 'Local Pool PowerTaker',
  'admin.contracts.navPillContract': 'Contract',
  'admin.contracts.navPillCustomer': 'Customer',
  'admin.contracts.navPillContractor': 'Contractor',
  'admin.contracts.navPillTariffs': 'Tariffs',
  'admin.contracts.navPillPayments': 'Payments',
  'admin.contracts.contractNumber': 'Contract number',
  'admin.contracts.onboarding': 'Onboarding',
  'admin.contracts.active': 'Active',
  'admin.contracts.terminated': 'Terminated',
  'admin.contracts.ended': 'Ended',
  'admin.contracts.backPowertakers': 'Powertakers',
  'admin.contracts.navActivePowertakers': 'Active',
  'admin.contracts.navPastPowertakers': 'Ended',
  'admin.contracts.headerContactInfo': 'Contact info',
  'admin.contracts.headerContractsList': 'Contracts list',
  'admin.contracts.objectTypePowerGiver': 'Powergiver',
  'admin.contracts.objectTypePowerRegister': 'Register',
  'admin.contracts.objectTypePowerTaker': 'Powertaker',
  'admin.contracts.headerContractsDetails': 'Contract details',
  'admin.contracts.registerName': 'Register name',
  'admin.contracts.meterSerial': 'Meter serial',
  'admin.contracts.customer': 'Customer',
  'admin.contracts.customerNumber': 'Customer number',
  'admin.contracts.contractor': 'Contractor',
  'admin.contracts.forecastKwhPa': 'Forecast',
  'admin.contracts.headerDates': 'Contract dates',
  'admin.contracts.terminationDate': 'Termination date',
};
