export default {
  'admin.contracts.register': 'Register',
  'admin.contracts.status': 'Status',
  'admin.contracts.forecastWattHour': 'Estimate',
  'admin.contracts.beginDate': 'Customer since',
  'admin.contracts.headerContractData': 'Contract Data',
  'admin.contracts.fullContractNumber': 'Contract number',
  'admin.contracts.endDate': 'End date',
  'admin.contracts.lastDate': 'End date',
  'admin.contracts.signingDate': 'Signed on',
  'admin.contracts.signingUser': 'Signed by',
  'admin.contracts.cancelationDate': 'Canceled on',
  'admin.contracts.headerBillingBasis': 'Billing basis',
  'admin.contracts.forecastWattHourPa': 'Estimated consumption',
  'admin.contracts.renewableEnergyLawTaxation': 'EEG calculation',
  'admin.contracts.thirdPartyBillingNumber': 'Invoice reference',
  'admin.contracts.thirdPartyRenterNumber': 'Tenant reference',
  'admin.contracts.headerSupplierChange': 'Supplier change',
  'admin.contracts.oldSupplierName': 'Prior supplier',
  'admin.contracts.oldCustomerNumber': 'Prior customer number',
  'admin.contracts.oldAccountNumber': 'Prior account number',
  'admin.contracts.headerGroupContracts': 'Contracts',
  'admin.contracts.descriptionGroupContracts':
    'List of all contracts for local group',
  'admin.contracts.tableType': 'Type',
  'admin.contracts.tableStatus': 'Status',
  'admin.contracts.tableSince': 'Begin',
  'admin.contracts.tableNumber': 'Contract #',
  'admin.contracts.tableName': 'Name',
  'admin.contracts.tableMarketLocation': 'MaLo',
  'admin.contracts.tableGroupName': 'Group name',
  'admin.contracts.tableRegisterName': 'Register name',
  'admin.contracts.tableContractNumber': 'Contract number',
  'admin.contracts.tableBeginDate': 'Start',
  'admin.contracts.tableEndDate': 'End',
  'admin.contracts.contract_metering_point_operator': 'Metering Point Operator',
  'admin.contracts.contract_localpool_processing': 'Local Pool Processing',
  'admin.contracts.contract_localpool_power_taker': 'Local Pool PowerTaker',
  'admin.contracts.navPillContract': 'Contract',
  'admin.contracts.navPillCustomer': 'Customer',
  'admin.contracts.navPillContractor': 'Contractor',
  'admin.contracts.navPillTariffs': 'Tariffs',
  'admin.contracts.navPillPayments': 'Payments',
  'admin.contracts.contractNumber': 'Contract number',
  'admin.contracts.onboarding': 'Onboarding',
  'admin.contracts.active': 'Active',
  'admin.contracts.terminated': 'Terminated',
  'admin.contracts.ended': 'Ended',
  'admin.contracts.signed': 'Signed',
  'admin.contracts.backPowertakers': 'Powertakers',
  'admin.contracts.navActivePowertakers': 'Active',
  'admin.contracts.navPastPowertakers': 'Ended',
  'admin.contracts.headerContactInfo': 'Contact info',
  'admin.contracts.headerContractsList': 'Contracts list',
  'admin.contracts.objectTypePowerGiver': 'Powergiver',
  'admin.contracts.objectTypePowerRegister': 'Register',
  'admin.contracts.objectTypePowerTaker': 'Powertaker',
  'admin.contracts.objectTypeMarketLocation': 'Consumption point',
  'admin.contracts.headerContractsDetails': 'Contract details',
  'admin.contracts.registerName': 'Register name',
  'admin.contracts.marketLocation': 'Consumption point',
  'admin.contracts.meterSerial': 'Meter serial',
  'admin.contracts.customer': 'Customer',
  'admin.contracts.customerNumber': 'Customer number',
  'admin.contracts.contractor': 'Contractor',
  'admin.contracts.forecastKwhPa': 'Forecast',
  'admin.contracts.headerDates': 'Contract dates',
  'admin.contracts.terminationDate': 'Termination date',
  'admin.contracts.F': 'full',
  'admin.contracts.R': 'reduced',
  'admin.contracts.N': 'null',
  'admin.contracts.thirdPartyContractor': 'Third party',
  'admin.contracts.modalHeaderAdd': 'Add contract',
  'admin.contracts.navBills': 'Bills',
  'admin.contracts.navContracts': 'Contracts',
  'admin.contracts.navBureaucracy': 'Bureaucracy',
  'admin.contracts.addNew': 'Create contract',
  'admin.contracts.modalHeaderUpload': 'Upload document',
  'admin.contracts.dropDocumentsHere': 'Drop documents here',
  'admin.contracts.createdAt': 'Created',
  'admin.contracts.updatedAt': 'Updated',
  'admin.contracts.taxNumber': 'Tax number',
  'admin.contracts.noGroupOwnerError': 'Please, add the group owner',
  'admin.contracts.headerAddPowertaker': 'Add powertaker',
  'admin.contracts.originalSigningUser': 'Signing user',
  'admin.contracts.mandateReference': 'Mandate reference',
  'admin.contracts.confirmPricingModel': 'Confirm pricing model',
  'admin.contracts.powerOfAttorney': 'Power of attorney',
  'admin.contracts.otherContract': 'Other contract',
  'admin.contracts.moveIn': 'Move in',
  'admin.contracts.authorization': 'Authorization',
  'admin.contracts.meteringPointOperatorName': 'MPO name',
  'admin.contracts.energyConsumptionBeforeKwhPa': 'Energy consumption before',
  'admin.contracts.downPaymentBeforeCentsPerMonth': 'Down payment before',
  'admin.contracts.shareRegisterWithGroup': 'Share register with group',
  'admin.contracts.shareRegisterPublicly': 'Share register publicly',
  'admin.contracts.registerMeta.name': 'MaLo name',
  'admin.contracts.registerMeta.label': 'MaLo label',
  'admin.contracts.CONSUMPTION': 'Consumption',
  'admin.contracts.CONSUMPTION_COMMON': 'Consumption common',
  'admin.contracts.DEMARCATION_PV': 'Demarcation PV',
  'admin.contracts.DEMARCATION_CHP': 'Demarcation CHP',
  'admin.contracts.DEMARCATION_WIND': 'Demarcation WIND',
  'admin.contracts.DEMARCATION_WATER': 'Demarcation WATER',
  'admin.contracts.PRODUCTION_PV': 'Production PV',
  'admin.contracts.PRODUCTION_CHP': 'Production CHP',
  'admin.contracts.PRODUCTION_WIND': 'Production WIND',
  'admin.contracts.PRODUCTION_WATER': 'Production WATER',
  'admin.contracts.GRID_CONSUMPTION': 'Grid consumption',
  'admin.contracts.GRID_FEEDING': 'Grid feeding',
  'admin.contracts.GRID_CONSUMPTION_CORRECTED': 'Grid consumption corrected',
  'admin.contracts.GRID_FEEDING_CORRECTED': 'Grid feeding corrected',
  'admin.contracts.OTHER': 'Other',
};
