export default {
  'admin.devices.modalHeaderAdd': 'Add device',
  'admin.devices.twoWayMeter': 'Two way meter',
  'admin.devices.twoWayMeterUsed': 'Two way meter used',
  'admin.devices.primaryEnergy': 'Primary energy',
  'admin.devices.commissioning': 'Commissioning',
  'admin.devices.law': 'Law',
  'admin.devices.manufacturer': 'Manufacturer',
  'admin.devices.kwPeak': 'kW peak',
  'admin.devices.kwhPerAnnum': 'kWh per annum',
  'admin.devices.addNew': 'Add new device',
  'admin.devices.tablePrimaryEnergy': 'Primary energy',
  'admin.devices.tableManufacturer': 'Manufacturer',
  'admin.devices.tableStatus': 'Status',
  'admin.devices.tableKwPeak': 'kW peak',
  'admin.devices.tableLaw': 'Law',
  'admin.devices.tableCommissioning': 'Commissioning',
  'admin.devices.yes': 'Yes',
  'admin.devices.planned': 'Planned',
  'admin.devices.bio_mass': 'Bio mass',
  'admin.devices.bio_gas': 'Bio gas',
  'admin.devices.natural_gas': 'Natural gas',
  'admin.devices.fluid_gas': 'Fluid gas',
  'admin.devices.fuel_oil': 'Fuel oil',
  'admin.devices.wood': 'Wood',
  'admin.devices.veg_oil': 'Veg oil',
  'admin.devices.sun': 'Sun',
  'admin.devices.wind': 'Wind',
  'admin.devices.water': 'Water',
  'admin.devices.other': 'Other',
  'admin.devices.eeg': 'EEG',
  'admin.devices.kwkg': 'KWKG',
  'admin.devices.free': 'Free',
  'admin.devices.electricitySupplier.id': 'Electricity supplier',
};
