export default {
  'admin.groups.tableName': 'Group name',
  'admin.groups.tableEnergyType': 'Energy sources',
  'admin.groups.headerSettings': 'Settings',
  'admin.groups.headerGroup': 'Group',
  'admin.groups.name': 'Name',
  'admin.groups.energySources': 'Energy sources',
  'admin.groups.startDate': 'Start date',
  'admin.groups.headerGroupsList': 'Your groups',
  'admin.groups.breadcrumbsMyLocalpools': 'My groups',
  'admin.groups.distributionSystemOperator': 'DSO',
  'admin.groups.transmissionSystemOperator': 'TSO',
  'admin.groups.electricitySupplier': 'ES',
  'admin.groups.visibility': 'Visibility',
  'admin.groups.showObject': 'Object',
  'admin.groups.showProduction': 'Production',
  'admin.groups.showEnergy': 'Energy',
  'admin.groups.showContact': 'Contact',
  'admin.groups.headerPowergiver': 'Powergiver',
  'admin.groups.bankAccount': 'Bank account',
  'admin.groups.customerNumber': 'Customer number',
  'admin.groups.statProduction': 'Production',
  'admin.groups.statConsumption': 'Consumption',
  'admin.groups.statAutarchy': 'Autarchy',
  'admin.groups.showDisplayApp': 'Show display app',
  'admin.groups.headerGapCustomer': 'Gap contract customer',
  'admin.groups.navGroupSettings': 'Group',
  'admin.groups.navPowergiver': 'Powergiver',
  'admin.groups.navBank': 'Bank',
  'admin.groups.navGapContact': 'GCC',
  'admin.groups.owner': 'Group owner',
  'admin.groups.menuAddGroup': 'Create group',
  'admin.groups.modalHeaderAdd': 'Create group',
  'admin.groups.confirmDeleteGroup': 'Are you sure that you want to delete: {name}?',
  'admin.groups.navFakeStats': 'Energy labelling',
  'admin.groups.navComments': 'Comments'
};
