export default {
  'admin.groups.tableName': 'Group name',
  'admin.groups.tableEnergyType': 'Energy sources',
  'admin.groups.headerSettings': 'Settings',
  'admin.groups.headerGroup': 'Group',
  'admin.groups.name': 'Name',
  'admin.groups.energySources': 'Energy sources',
  'admin.groups.startDate': 'Start date',
  'admin.addresses.address': 'Address',
  'admin.groups.headerGroupsList': 'Your groups',
  'admin.groups.breadcrumbsMyLocalpools': 'My groups',
  'admin.groups.distributionSystemOperator': 'DSO',
  'admin.groups.transmissionSystemOperator': 'TSO',
  'admin.groups.electricitySupplier': 'ES',
  'admin.groups.visibility': 'Visibility',
  'admin.groups.showObject': 'Object',
  'admin.groups.showProduction': 'Production',
  'admin.groups.showEnergy': 'Energy',
  'admin.groups.showContact': 'Contact',
  'admin.groups.headerPowergiver': 'Powergiver',
};
