export default {
  'admin.persons.phone': 'Phone',
  'admin.persons.email': 'Email',
  'admin.persons.lastLogin': 'Last login',
  'admin.persons.headerContact': 'Contact person',
  'admin.persons.prefix': 'Prefix',
  'admin.persons.title': 'Title',
  'admin.persons.firstName': 'First name',
  'admin.persons.lastName': 'Last name',
  'admin.persons.mandateReference': 'SEPA reference',
  'admin.persons.F': 'Mrs.',
  'admin.persons.M': 'Mr.',
  'admin.persons.Dr.': 'Dr.',
  'admin.persons.Prof.': 'Prof.',
  'admin.persons.Prof.Dr': 'Prof.Dr.',
  'admin.persons.headerMyProfile': 'My Profile',
  'admin.persons.headerBankAccounts': 'Bank accounts',
  'admin.persons.descriptionBankAccounts': 'Bank accounts for billing',
  'admin.persons.navPillContactInfo': 'Contact Info',
  'admin.persons.navPillAccount': 'Account',
  'admin.persons.navPillBank': 'Bank Accounts',
};
