export default {
  'admin.readings.date': 'Reading date',
  'admin.readings.wattHour': 'Value',
  'admin.readings.rawValue': 'Raw value',
  'admin.readings.value': 'Value',
  'admin.readings.unit': 'Unit',
  'admin.readings.reason': 'Reason',
  'admin.readings.readBy': 'Reading by',
  'admin.readings.quality': 'Quality',
  'admin.readings.source': 'Source',
  'admin.readings.status': 'State',
  'admin.readings.comment': 'Comment',
  'admin.readings.Wh': 'Wh',
  'admin.readings.W': 'W',
  'admin.readings.m³': 'm³',
  'admin.readings.IOM': 'Installation of meter',
  'admin.readings.COM1': 'Change of meter 1',
  'admin.readings.COM2': 'Change of meter 2',
  'admin.readings.ROM': 'Removal of meter',
  'admin.readings.PMR': 'Periodic meter reading',
  'admin.readings.COT': 'Intermediate reading',
  'admin.readings.COS': 'Change of service',
  'admin.readings.CMP': 'Change of meter parameter',
  'admin.readings.COB': 'Change of balance region',
  'admin.readings.BN': 'Buzzn',
  'admin.readings.SN': 'Powertaker',
  'admin.readings.SG': 'Powergiver',
  'admin.readings.VNB': 'Distribution system operator',
  'admin.readings.20': 'Unusable value',
  'admin.readings.67': 'Substitute (estimated)',
  'admin.readings.79': 'Energy summed',
  'admin.readings.187': 'Prognosis',
  'admin.readings.220': 'Reading',
  'admin.readings.201': 'Suggested value',
  'admin.readings.SM': 'SmartMeter',
  'admin.readings.MAN': 'Manual',
  'admin.readings.Z83': 'Z83 - Customer reading',
  'admin.readings.Z84': 'Z84 - Empty',
  'admin.readings.Z86': 'Z86 - Plausible',
  'admin.readings.headerReading': 'Reading',
  'admin.readings.tableDate': 'Date',
  'admin.readings.tableValue': 'Value',
  'admin.readings.tableReason': 'Reason',
  'admin.readings.addNew': 'Add new reading',
  'admin.readings.modalHeaderAdd': 'Add new reading',
};
