export default {
  'admin.register_metas.name': 'Name',
  'admin.register_metas.label': 'Label',
  'admin.register_metas.DEMARCATION_PV': 'Demarcation PV',
  'admin.register_metas.DEMARCATION_CHP': 'Demarcation CHP',
  'admin.register_metas.DEMARCATION_WATER': 'Water Demarcation',
  'admin.register_metas.DEMARCATION_WIND': 'Wind Demarcation',
  'admin.register_metas.PRODUCTION_PV': 'Production PV',
  'admin.register_metas.PRODUCTION_CHP': 'Produktion CHP',
  'admin.register_metas.PRODUCTION_WATER': 'Produktion Water',
  'admin.register_metas.PRODUCTION_WIND': 'Produktion Wind',
  'admin.register_metas.GRID_CONSUMPTION': 'Grid consumption',
  'admin.register_metas.GRID_FEEDING': 'Grid Feed-in',
  'admin.register_metas.GRID_CONSUMPTION_CORRECTED': 'Grid consumption corrected',
  'admin.register_metas.GRID_FEEDING_CORRECTED': 'Grid Feed-in korrigiert',
  'admin.register_metas.OTHER': 'Other',
  'admin.register_metas.CONSUMPTION': 'Consumption',
  'admin.register_metas.CONSUMPTION_COMMON': 'Consumption - Common',
};
