export default {
  'admin.registers.meteringPointId': 'Metering Point Id',
  'admin.registers.type': 'Type',
  'admin.registers.register_real': 'Real',
  'admin.registers.register_virtual': 'Virtual',
  'admin.registers.name': 'Name',
  'admin.registers.label': 'Label',
  'admin.registers.DEMARCATION_PV': 'Demarcation PV',
  'admin.registers.DEMARCATION_CHP': 'Demarcation CHP',
  'admin.registers.DEMARCATION_WATER': 'Water Demarcation',
  'admin.registers.DEMARCATION_WIND': 'Wind Demarcation',
  'admin.registers.PRODUCTION_PV': 'Production PV',
  'admin.registers.PRODUCTION_CHP': 'Produktion CHP',
  'admin.registers.PRODUCTION_WATER': 'Produktion Water',
  'admin.registers.PRODUCTION_WIND': 'Produktion Wind',
  'admin.registers.GRID_CONSUMPTION': 'Grid consumption',
  'admin.registers.GRID_FEEDING': 'Grid Feed-in',
  'admin.registers.GRID_CONSUMPTION_CORRECTED': 'Grid consumption corrected',
  'admin.registers.GRID_FEEDING_CORRECTED': 'Grid Feed-in korrigiert',
  'admin.registers.OTHER': 'Other',
  'admin.registers.CONSUMPTION': 'Consumption',
  'admin.registers.CONSUMPTION_COMMON': 'Consumption - Common',
  'admin.registers.direction': 'Direction',
  'admin.registers.in': 'Feed-In',
  'admin.registers.out': 'Draw',
  'admin.registers.obis': 'OBIS',
  'admin.registers.preDecimalPosition': 'Pre-decimal position',
  'admin.registers.postDecimalPosition': 'Post-decimal position',
  'admin.registers.lowLoadAbility': 'Low load ability',
  'admin.registers.observerEnabled': 'Observation enabled',
  'admin.registers.observerMinThreshold': 'Minimum threshold',
  'admin.registers.observerMaxThreshold': 'Maximum threshold',
  'admin.registers.observerOfflineMonitoring': 'Offline alert',
  'admin.registers.lastObserved': 'Last observation on',
  'admin.registers.headerRegisterData': 'Register Data',
  'admin.registers.headerObservation': 'Observation',
  'admin.registers.navPillRegisterData': 'Register Data',
  'admin.registers.navPillReadings': 'Readings',
  'admin.registers.navPillFormula': 'Formula',
  'admin.registers.tableName': 'Name',
  'admin.registers.tableMeteringPointId': 'Metering point id',
  'admin.registers.tableDirection': 'Direction',
  'admin.registers.tableLabel': 'Label',
  'admin.registers.headerRegisterPower': 'Power',
  'admin.registers.headerRegisterDetails': 'Register details',
  'admin.registers.headerEdifactInformation': 'EDIFACT information',
  'admin.registers.navReadings': 'Readings',
  'admin.registers.navContracts': 'Contracts',
  'admin.registers.navDevices': 'Devices',
  'admin.registers.navDetails': 'Details',
  'admin.registers.tableObis': 'OBIS',
  'admin.registers.tableKind': 'Kind',
  'admin.registers.marketLocationId': 'MaLo ID',
};
