export default {
  'admin.tariffs.pricing': 'Pricing',
  'admin.tariffs.name': 'Tariff',
  'admin.tariffs.beginDate': 'Begin date',
  'admin.tariffs.endDate': 'End date',
  'admin.tariffs.energyPricePerKw': 'Price per kWh',
  'admin.tariffs.nbasePricePerMonth': 'Base price per month',
  'admin.tariffs.headerTariffData': 'Tariff data',
  'admin.tariffs.backTariffs': 'Tariffs',
  'admin.tariffs.navActiveTariffs': 'Active',
  'admin.tariffs.navPastTariffs': 'Past',
  'admin.tariffs.tableName': 'Name',
  'admin.tariffs.tableBeginDate': 'Start date',
  'admin.tariffs.tableEndDate': 'End date',
  'admin.tariffs.tableBasepriceCentsPerMonth': 'Base/month, net',
  'admin.tariffs.tableEnergypriceCentsPerKwh': 'Base/kwh, net',
  'admin.tariffs.numberOfContracts': 'Number of contracts',
  'admin.tariffs.energypriceCentsPerKwh': 'Base/kwh',
  'admin.tariffs.basepriceCentsPerMonth': 'Base/month',
  'admin.tariffs.addNew': 'Add new tariff',
  'admin.tariffs.modalHeaderAdd': 'Add new tariff',
};
