export default {
  'en-US': {
    'powertakerForm.complete': 'Complete',
    'powertakerForm.pre.zip': 'Where is your reference point?',
    'powertakerForm.pre.kwh': 'How much electricity will you consume?',
    'powertakerForm.pre.type': 'What counter type do you have?',
    'powertakerForm.title.dr': 'Dr.',
    'powertakerForm.title.drHabil': 'Dr. habil.',
    'powertakerForm.title.prof': 'Prof.',
    'powertakerForm.gender.male': 'Male',
    'powertakerForm.gender.female': 'Female',
    'powertakerForm.gender.unknown': 'No information',
    'powertakerForm.cateringPermit.no': 'No',
    'powertakerForm.cateringPermit.unknown': `I don't know`,
    'powertakerForm.cateringPermit.yes': 'Yes',
    'powertakerForm.contractorAddress.other': 'Other address',
    'powertakerForm.contractorAddress.same': 'Same address as contract partner (see above)',
    'powertakerForm.legalEntity.company': 'An organization (company, cooperative, association or even married people, family, WEG etc.)',
    'powertakerForm.legalEntity.person': 'I myself as a natural person (also as a freelancer)',
    'powertakerForm.moveIn.no': 'No',
    'powertakerForm.moveIn.yes': 'Yes',
    'powertakerForm.newMeterOperator.no': 'No',
    'powertakerForm.newMeterOperator.unknown': `I don't know`,
    'powertakerForm.newMeterOperator.yes': 'Yes',
    'powertakerForm.reseller.no': 'No',
    'powertakerForm.reseller.unknown': `I don't know`,
    'powertakerForm.reseller.yes': 'Yes',
    'powertakerForm.virtualCounter.no': 'No',
    'powertakerForm.virtualCounter.unknown': `I don't know`,
    'powertakerForm.virtualCounter.yes': 'Yes',
    'powertakerForm.field.energypriceCentsPerKilowattHour': 'Your working rate [Ct / kWh]',
    'powertakerForm.field.basepriceCentsPerMonth': 'Your basic price [€ / month]',
    'powertakerForm.field.totalCentsPerMonth': 'Your estimated discount [€ / month]',
    'powertakerForm.text.prices': 'All prices include all statutory duties, taxes and levies.',
    'powertakerForm.header.person': 'Contact Person',
    'powertakerForm.field.profileTitle': 'Title',
    'powertakerForm.field.profileFirstName': 'First name',
    'powertakerForm.field.profileLastName': 'Last name',
    'powertakerForm.field.profileGender': 'Gender',
    'powertakerForm.field.profilePhone': 'Phone',
    'powertakerForm.header.contractingParty': 'Contract partners',
    'powertakerForm.field.contractingPartyLegalEntity': 'Who should become a contract partner?',
    'powertakerForm.field.companyOrganizationName': 'Name of the organization',
    'powertakerForm.field.companyOrganizationRepresentedBy': 'Represented by',
    'powertakerForm.field.companyOrganizationEmail': 'E-mail (central mailbox)',
    'powertakerForm.field.companyAuthorizationTitle': 'Authorization',
    'powertakerForm.field.companyAuthorizationLabel': 'I am a contact person and is entitled to conclude power supply contracts for the above mentioned organization.',
    'powertakerForm.field.addressStreetName': 'Street (contract partner)',
    'powertakerForm.field.addressStreetNumber': 'House number (contractor)',
    'powertakerForm.field.addressAddress': 'Additional address (contract partner)',
    'powertakerForm.field.addressZip': 'Postal code (contract partner)',
    'powertakerForm.field.addressCity': 'City (contract partner)',
    'powertakerForm.field.addressState': 'State (Contract partner)',
    'powertakerForm.field.contractingPartyProviderPermission': 'Do you own a utility license?',
    'powertakerForm.field.companyOrganizationRetailer': 'Are your reseller?',
    'powertakerForm.field.contractOtherContract': 'I / we already have a power supply contract with buzzn',
    'powertakerForm.header.referencePoint': 'Reference point',
    'powertakerForm.field.contractorAddress': 'Where do you want to buy buzzn electricity?',
    'powertakerForm.field.otherAddressStreetName': 'Street (reference point)',
    'powertakerForm.field.otherAddressStreetNumber': 'House number (reference point)',
    'powertakerForm.field.otherAddressAddress': 'Additional address (reference point)',
    'powertakerForm.field.otherAddressZip': 'Postal code (reference point)',
    'powertakerForm.field.otherAddressCity': 'City (reference point)',
    'powertakerForm.field.otherAddressState': 'State (reference point)',
    'powertakerForm.field.meterSerialNumber': 'Counter number',
    'powertakerForm.field.meterProductName': 'Counter name',
    'powertakerForm.field.meterMeteringType': 'Counter type',
    'powertakerForm.field.meteringPointVirtual': 'Is the counter virtual?',
    'powertakerForm.field.contractMoveIn': 'Do you re-enter there?',
    'powertakerForm.field.contractBeginning': 'Day of first delivery',
    'powertakerForm.field.oldContractOldName': 'From which supplier has electricity been supplied so far?',
    'powertakerForm.field.oldContractCustomerNumber': 'What is your customer number with the previous supplier?',
    'powertakerForm.field.oldContractContractNumber': 'What is your contract account number with the previous supplier?',
    'powertakerForm.field.contractYearlyKwh': 'Consumption prognosis',
    'powertakerForm.field.newMeterOperator': 'Did you assign a new measuring point operator for the reference point?',
    'powertakerForm.field.contractMeteringPointOperator': 'Name of the measuring point operator',
    'powertakerForm.field.bankAccountHolder': 'account owner',
    'powertakerForm.field.bankAccountDirectDebitTitle': 'SEPA direct debit mandate',
    'powertakerForm.field.bankAccountDirectDebitLabel': 'I revocably revoke payments from the above account using SEPA Base Loan. At the same time, I instruct my bank to pay the debts drawn by buzzn from my account. I can demand reimbursement of the debited amount within eight weeks, beginning with the debit date. The conditions agreed with my bank apply.',
    'powertakerForm.field.contractPowerOfAttorneyTitle': 'Power of attorney',
    'powertakerForm.field.contractPowerOfAttorneyLabel': 'Herewith I give buzzn Vollmacht',
    'powertakerForm.field.contractTermsTitle': 'Terms and Conditions (GTC)',
    'powertakerForm.field.contractTermsLabel': 'Yes, I have received the terms and conditions and I agree with them',
    'powertakerForm.field.contractMessageToBuzzn': 'My message to the buzzn team:',
    'powertakerForm.field.contractHearAboutBuzzn': 'How did you hear about buzzn?',
  },
};
