export default {
  'admin.bankAccounts.tableAccountName': 'Name',
  'admin.bankAccounts.tableBankName': 'Bank',
  'admin.bankAccounts.tableEncryptedIban': 'IBAN',
  'admin.bankAccounts.tableStatus': 'Status',
  'admin.bankAccounts.holder': 'pleaseTranslate Holder',
  'admin.bankAccounts.bic': 'BIC',
  'admin.bankAccounts.iban': 'IBAN',
  'admin.bankAccounts.bankName': 'pleaseTranslate Bank name',
  'admin.bankAccounts.directDebit': 'pleaseTranslate Direct debit',
  'admin.bankAccounts.modalHeaderAdd': 'pleaseTranslate Create bank account',
  'admin.bankAccounts.headerBankAccounts': 'Bank accounts',
  'admin.bankAccounts.addNew': 'Create bank account',
  'admin.bankAccounts.tableHolder': 'Holder',
  'admin.bankAccounts.tableBic': 'BIC',
  'admin.bankAccounts.tableIban': 'IBAN',
  'admin.bankAccounts.tableDirectDebit': 'Direc Debit',
};
