export default {
  'admin.bankAccounts.tableAccountName': 'Name',
  'admin.bankAccounts.tableBankName': 'Bank',
  'admin.bankAccounts.tableEncryptedIban': 'IBAN',
  'admin.bankAccounts.tableStatus': 'Status',
  'admin.bankAccounts.holder': 'Kontoinhaber',
  'admin.bankAccounts.bic': 'BIC',
  'admin.bankAccounts.iban': 'IBAN',
  'admin.bankAccounts.bankName': 'Bank name',
  'admin.bankAccounts.directDebit': 'Lastschrift',
  'admin.bankAccounts.modalHeaderAdd': 'Bankkonto erstellen',
  'admin.bankAccounts.headerBankAccounts': 'Bankkonten',
  'admin.bankAccounts.addNew': 'Bankkonto erstellen',
  'admin.bankAccounts.tableHolder': 'Kontoinhaber',
  'admin.bankAccounts.tableBic': 'BIC',
  'admin.bankAccounts.tableIban': 'IBAN',
  'admin.bankAccounts.tableDirectDebit': 'Lastschrift',
};
