export default {
  'admin.billings.titleDetails': 'Rechnungsdaten',
  'admin.billings.customerName': 'Stromnehmer',
  'admin.billings.dateRange': 'Abrechnungszeitraum',
  'admin.billings.customerEmail': 'Emailadresse',
  'admin.billings.status': 'Status',
  'admin.billings.titleReference': 'Bezugsmenge',
  'admin.billings.tableMeterSerial': 'Zählernummer',
  'admin.billings.tableDates': 'Zeitraum',
  'admin.billings.tableBeginReadingKwh': 'Zählerstand Beginn',
  'admin.billings.tableEndReadingKwh': 'Zählerstand Ende',
  'admin.billings.tableConsumedEnergyKwh': 'Bezugsmenge',
  'admin.billings.tableDesignation': 'Bezeichung',
  'admin.billings.tableAmount': 'Menge',
  'admin.billings.tableUnit': 'Einheit',
  'admin.billings.tablePriceForUnit': 'Preis je einheit',
  'admin.billings.tableNetAmount': 'Nettobetrag',
  'admin.billings.titleInvoices': 'Abrechnung',
  'admin.billings.basePrice': 'Grundpreis',
  'admin.billings.workingPrice': 'Arbeitspreis',
  'admin.billings.tableInvoiceNumber': 'Rechnungsnummer',
  'admin.billings.tableBeginDate': 'Startdatum',
  'admin.billings.tableEndDate': 'Enddatum',
  'admin.billings.tableStatus': 'Status',
  'admin.billings.addNew': 'Rechnung hinzufügen',
  'admin.billings.modalHeaderAdd': 'Neue Rechnung hinzufügen',
  'admin.billings.beginDate': 'Startdatum',
  'admin.billings.endDate': 'Enddatum',
  'admin.billings.invoiceNumber': 'Rechnungsnummer',
  'admin.billings.open': 'Offen',
  'admin.billings.calculated': 'Berechnet',
  'admin.billings.delivered': 'Zugestellt',
  'admin.billings.settled': 'Abgewickelt',
  'admin.billings.closed': 'Geschlossen',
  'admin.billings.headerBillingItems': 'Rechnungsobjekte',
};
