export default {
  'admin.billings.titleDetails': 'Rechnungsdaten',
  'admin.billings.customerName': 'Stromnehmer',
  'admin.billings.dateRange': 'Abrechnungszeitraum',
  'admin.billings.customerEmail': 'Emailadresse',
  'admin.billings.status': 'Status',
  'admin.billings.titleReference': 'Bezugsmenge',
  'admin.billings.tableMeterSerial': 'Zählernummer',
  'admin.billings.tableDates': 'Zeitraum',
  'admin.billings.tableBeginReadingKwh': 'Zählerstand Beginn',
  'admin.billings.tableEndReadingKwh': 'Zählerstand Ende',
  'admin.billings.tableConsumedEnergyKwh': 'Bezugsmenge',
  'admin.billings.tableDesignation': 'Bezeichung',
  'admin.billings.tableAmount': 'Menge',
  'admin.billings.tableUnit': 'Einheit',
  'admin.billings.tablePriceForUnit': 'Preis je einheit',
  'admin.billings.tableNetAmount': 'Nettobetrag',
  'admin.billings.titleInvoices': 'Abrechnung',
  'admin.billings.basePrice': 'Grundpreis',
  'admin.billings.workingPrice': 'Arbeitspreis',
  'admin.billings.tableInvoiceNumber': 'pleaseTranslate Invoice Num',
  'admin.billings.tableBeginDate': 'pleaseTranslate Begin Date',
  'admin.billings.tableEndDate': 'pleaseTranslate End Date',
  'admin.billings.tableStatus': 'pleaseTranslate Status',
  'admin.billings.addNew': 'pleaseTranslate Add new billing',
  'admin.billings.modalHeaderAdd': 'pleaseTranslate Add new billing',
  'admin.billings.beginDate': 'pleaseTranslate Begin Date',
  'admin.billings.endDate': 'pleaseTranslate End Date',
  'admin.billings.invoiceNumber': 'pleaseTranslate Invoice number',
  'admin.billings.open': 'pleaseTranslate open',
  'admin.billings.calculated': 'pleaseTranslate calculated',
  'admin.billings.delivered': 'pleaseTranslate delivered',
  'admin.billings.settled': 'pleaseTranslate settled',
  'admin.billings.closed': 'pleaseTranslate closed',
  'admin.billings.headerBillingItems': 'pleaseTranslate Billing Items',
};
