export default {
  'admin.billingCycles.backBillingCycles': 'Turnusabrechnungen',
  'admin.billingCycles.addNew': 'Turnusabrechnung erstellen',
  'admin.billingCycles.modalHeaderAdd': 'Neue Turnusabrechnung',
  'admin.billingCycles.tableName': 'Name',
  'admin.billingCycles.tableDates': 'Zeitraum',
  'admin.billingCycles.maloListTitle': 'Bezugsstelle',
  'admin.billingCycles.barsLegendTitle': 'Legende',
  'admin.billingCycles.barsLegendClosed': 'Abgerechnet',
  'admin.billingCycles.barsLegendVoid': 'Void',
  'admin.billingCycles.barsLegendSettled': 'Settled',
  'admin.billingCycles.barsLegendDelivered': 'Delivered',
  'admin.billingCycles.barsLegendQueued': 'Queued',
  'admin.billingCycles.barsLegendDocumented': 'Documented',
  'admin.billingCycles.barsLegendCalculated': 'Calculated',
  'admin.billingCycles.barsLegendOpen': 'Offen',
  'admin.billingCycles.barsLegendPT': 'Stromnehmervertrag',
  'admin.billingCycles.barsLegendGAP': 'Leerstandsvertrag',
  'admin.billingCycles.barsLegendTP': 'Drittbelieferte',
};
