export default {
  'admin.contracts.register': 'Zählwerk',
  'admin.contracts.status': 'Status',
  'admin.contracts.forecastWattHour': 'Schätzung',
  'admin.contracts.beginDate': 'Beginn',
  'admin.contracts.headerContractData': 'Vertragsdaten',
  'admin.contracts.fullContractNumber': 'Vertragsnummer',
  'admin.contracts.endDate': 'Ende',
  'admin.contracts.signingDate': 'Unterzeichnet am',
  'admin.contracts.signingUser': 'Unterzeichnet von',
  'admin.contracts.cancelationDate': 'Gekündigt am',
  'admin.contracts.headerBillingBasis': 'Abrechnungsgrundlage',
  'admin.contracts.forecastWattHourPa': 'Verbrauchsprognose',
  'admin.contracts.renewableEnergyLawTaxation': 'EEG Umlage',
  'admin.contracts.thirdPartyBillingNumber': 'Rechnungsnummer',
  'admin.contracts.thirdPartyRenterNumber': 'Mieternummer',
  'admin.contracts.headerSupplierChange': 'Wechseldaten',
  'admin.contracts.oldSupplierName': 'Vorlieferant',
  'admin.contracts.oldCustomerNumber': 'alte Kundennummer',
  'admin.contracts.oldAccountNumber': 'alte Vertragskontonummer',
  'admin.contracts.headerGroupContracts': 'Verträge',
  'admin.contracts.descriptionGroupContracts': 'Liste alle Verträge der lokalen Gruppe',
  'admin.contracts.tableType': 'Typ',
  'admin.contracts.tableStatus': 'Status',
  'admin.contracts.tableSince': 'Beginn',
  'admin.contracts.tableNumber': 'Vertragsnummer',
  'admin.contracts.contract_metering_point_operator': 'Metering Point Operator',
  'admin.contracts.contract_localpool_processing': 'Local Pool Processing',
  'admin.contracts.navPillContract': 'Vertrag',
  'admin.contracts.navPillCustomer': 'Vertragsnehmer',
  'admin.contracts.navPillContractor': 'Vertragsgeber',
  'admin.contracts.navPillTariffs': 'Tarife',
  'admin.contracts.navPillPayments': 'Abschlagszahlungen',
  'admin.contracts.contractNumber': 'Vertragsnummer',
};
