export default {
  'admin.contracts.register': 'Zählwerk',
  'admin.contracts.status': 'Status',
  'admin.contracts.forecastWattHour': 'Schätzung',
  'admin.contracts.beginDate': 'Beginn am',
  'admin.contracts.headerContractData': 'Vertragsdaten',
  'admin.contracts.fullContractNumber': 'Vertragsnummer',
  'admin.contracts.endDate': 'Endet am',
  'admin.contracts.lastDate': 'Endet am',
  'admin.contracts.signingDate': 'Unterzeichnet am',
  'admin.contracts.signingUser': 'Unterzeichnet von',
  'admin.contracts.cancelationDate': 'Gekündigt am',
  'admin.contracts.headerBillingBasis': 'Abrechnungsgrundlage',
  'admin.contracts.forecastWattHourPa': 'Verbrauchsprognose',
  'admin.contracts.renewableEnergyLawTaxation': 'EEG Umlage',
  'admin.contracts.thirdPartyBillingNumber': 'Rechnungsnummer',
  'admin.contracts.thirdPartyRenterNumber': 'Mieternummer',
  'admin.contracts.headerSupplierChange': 'Wechseldaten',
  'admin.contracts.oldSupplierName': 'Vorlieferant',
  'admin.contracts.oldCustomerNumber': 'alte Kundennummer',
  'admin.contracts.oldAccountNumber': 'alte Vertragskontonummer',
  'admin.contracts.headerGroupContracts': 'Verträge',
  'admin.contracts.descriptionGroupContracts':
    'Liste alle Verträge der lokalen Gruppe',
  'admin.contracts.tableType': 'Typ',
  'admin.contracts.tableStatus': 'Status',
  'admin.contracts.tableSince': 'Beginn',
  'admin.contracts.tableNumber': 'Vertragsnummer',
  'admin.contracts.contract_metering_point_operator': 'Messvertrag',
  'admin.contracts.contract_localpool_processing': 'Abwicklungsvertrag',
  'admin.contracts.contract_localpool_power_taker':
    'Lokaler Stromnehmervertrag',
  'admin.contracts.navPillContract': 'Vertrag',
  'admin.contracts.navPillCustomer': 'Vertragsnehmer',
  'admin.contracts.navPillContractor': 'Vertragsgeber',
  'admin.contracts.navPillTariffs': 'Tarife',
  'admin.contracts.navPillPayments': 'Abschlagszahlungen',
  'admin.contracts.contractNumber': 'Vertragsnummer',
  'admin.contracts.navActivePowertakers': 'Aktive Stromnehmer',
  'admin.contracts.navPastPowertakers': 'Ehemalige Stromnehmer',
  'admin.contracts.tableName': 'Name',
  'admin.contracts.tableMarketLocation': 'Bezugsstelle',
  'admin.contracts.tableGroupName': 'Gruppenname',
  'admin.contracts.tableRegisterName': 'Zählwerk',
  'admin.contracts.tableContractNumber': 'Vertragsnummer',
  'admin.contracts.tableBeginDate': 'Beginn',
  'admin.contracts.tableEndDate': 'Ende',
  'admin.contracts.tableStatus': 'Status',
  'admin.contracts.onboarding': 'Im Wechselprozess',
  'admin.contracts.active': 'In Belieferung',
  'admin.contracts.terminated': 'Gekündigt',
  'admin.contracts.ended': 'Beendet',
  'admin.contracts.signed': 'Unterzeichnet',
  'admin.contracts.backPowertakers': 'Stromnehmer',
  'admin.contracts.navActivePowertakers': 'Aktive Stromnehmer',
  'admin.contracts.navPastPowertakers': 'Ehemalige Stromnehmer',
  'admin.contracts.headerContactInfo': 'Kontaktinformation',
  'admin.contracts.headerContractsList': 'Verträge',
  'admin.contracts.objectTypePowerGiver': 'Stromgeber',
  'admin.contracts.objectTypePowerRegister': 'Zählwerk',
  'admin.contracts.objectTypePowerTaker': 'Stromnehmer',
  'admin.contracts.objectTypeMarketLocation': 'Bezugsstelle',
  'admin.contracts.headerContractsDetails': 'Details',
  'admin.contracts.registerName': 'Zählwerk',
  'admin.contracts.meterSerial': 'Zählernummer',
  'admin.contracts.marketLocation': 'Bezugsstelle',
  'admin.contracts.customer': 'Vertragsnehmer',
  'admin.contracts.customerNumber': 'Kundennummer',
  'admin.contracts.contractor': 'Vertragsgeber',
  'admin.contracts.forecastKwhPa': 'Prognostizierter Verbrauch',
  'admin.contracts.headerDates': 'Daten',
  'admin.contracts.terminationDate': 'Datum der Kündigung',
  'admin.contracts.F': 'voll',
  'admin.contracts.R': 'reduziert',
  'admin.contracts.N': 'keine',
  'admin.contracts.thirdPartyContractor': 'Drittbeliefert',
  'admin.contracts.modalHeaderAdd': 'Neuen Vertrag erstellen',
  'admin.contracts.navBills': 'Rechnungen',
  'admin.contracts.navContracts': 'Verträge',
  'admin.contracts.navBureaucracy': 'Bürokratie',
  'admin.contracts.addNew': 'Neuen Vertrag erstellen',
  'admin.contracts.modalHeaderUpload': 'Dokument hochladen',
  'admin.contracts.dropDocumentsHere': 'Klicken oder PDF hier hineinziehen',
  'admin.contracts.createdAt': 'Erzeugt',
  'admin.contracts.updatedAt': 'Aktualisiert',
  'admin.contracts.taxNumber': 'Steuernummer',
  'admin.contracts.noGroupOwnerError': 'Bitte einen Stromgeber zuweisen',
  'admin.contracts.headerAddPowertaker': 'pleaseTranslate Add powertaker',
  'admin.contracts.originalSigningUser': 'pleaseTranslate Signing user',
  'admin.contracts.mandateReference': 'pleaseTranslate Mandate reference',
  'admin.contracts.confirmPricingModel': 'pleaseTranslate Confirm pricing model',
  'admin.contracts.powerOfAttorney': 'pleaseTranslate Power of attorney',
  'admin.contracts.otherContract': 'pleaseTranslate Other contract',
  'admin.contracts.moveIn': 'pleaseTranslate Move in',
  'admin.contracts.authorization': 'pleaseTranslate Authorization',
  'admin.contracts.meteringPointOperatorName': 'pleaseTranslate MPO name',
  'admin.contracts.energyConsumptionBeforeKwhPa': 'pleaseTranslate Energy consumption before',
  'admin.contracts.downPaymentBeforeCentsPerMonth': 'pleaseTranslate Down payment before',
  'admin.contracts.shareRegisterWithGroup': 'pleaseTranslate Share register with group',
  'admin.contracts.shareRegisterPublicly': 'pleaseTranslate Share register publicly',
  'admin.contracts.registerMeta.name': 'pleaseTranslate MaLo name',
  'admin.contracts.registerMeta.label': 'pleaseTranslate MaLo label',
  'admin.contracts.CONSUMPTION': 'pleaseTranslate Consumption',
  'admin.contracts.CONSUMPTION_COMMON': 'pleaseTranslate Consumption common',
  'admin.contracts.DEMARCATION_PV': 'pleaseTranslate Demarcation PV',
  'admin.contracts.DEMARCATION_CHP': 'pleaseTranslate Demarcation CHP',
  'admin.contracts.DEMARCATION_WIND': 'pleaseTranslate Demarcation WIND',
  'admin.contracts.DEMARCATION_WATER': 'pleaseTranslate Demarcation WATER',
  'admin.contracts.PRODUCTION_PV': 'pleaseTranslate Production PV',
  'admin.contracts.PRODUCTION_CHP': 'pleaseTranslate Production CHP',
  'admin.contracts.PRODUCTION_WIND': 'pleaseTranslate Production WIND',
  'admin.contracts.PRODUCTION_WATER': 'pleaseTranslate Production WATER',
  'admin.contracts.GRID_CONSUMPTION': 'pleaseTranslate Grid consumption',
  'admin.contracts.GRID_FEEDING': 'pleaseTranslate Grid feeding',
  'admin.contracts.GRID_CONSUMPTION_CORRECTED': 'pleaseTranslate Grid consumption corrected',
  'admin.contracts.GRID_FEEDING_CORRECTED': 'pleaseTranslate Grid feeding corrected',
  'admin.contracts.OTHER': 'pleaseTranslate Other',
};
