export default {
  'admin.devices.modalHeaderAdd': 'Gerät hinzufügen',
  'admin.devices.twoWayMeter': 'Zweirichtungszähler',
  'admin.devices.twoWayMeterUsed': 'verwendeter Zweirichtungszähler',
  'admin.devices.primaryEnergy': 'Primärenergie',
  'admin.devices.commissioning': 'Inbetriebnahme',
  'admin.devices.law': 'Gesetz',
  'admin.devices.manufacturer': 'Hersteller',
  'admin.devices.kwPeak': 'kW peak',
  'admin.devices.kwhPerAnnum': 'kWh im Jahr',
  'admin.devices.addNew': 'neues Gerät hinzufügen',
  'admin.devices.tablePrimaryEnergy': 'Primärenergie',
  'admin.devices.tableManufacturer': 'Hersteller',
  'admin.devices.tableStatus': 'Status',
  'admin.devices.tableKwPeak': 'kW peak',
  'admin.devices.tableLaw': 'Gesetz',
  'admin.devices.tableCommissioning': 'Inbetriebnahme',
  'admin.devices.yes': 'Ja',
  'admin.devices.planned': 'pleaseTranslate Planned',
  'admin.devices.bio_mass': 'Biomasse',
  'admin.devices.bio_gas': 'Biogas',
  'admin.devices.natural_gas': 'Erdgas',
  'admin.devices.fluid_gas': 'Flüssiggas',
  'admin.devices.fuel_oil': 'Öl',
  'admin.devices.wood': 'Holz',
  'admin.devices.veg_oil': 'Pflanzenöl',
  'admin.devices.sun': 'Sonne',
  'admin.devices.wind': 'Wind',
  'admin.devices.water': 'Wasser',
  'admin.devices.other': 'andere',
  'admin.devices.eeg': 'EEG',
  'admin.devices.kwkg': 'KWKG',
  'admin.devices.free': 'ohne',
  'admin.devices.electricitySupplier.id': 'Stromanbieter',
  'admin.devices.headerDeviceDetails': 'Geräte Details',
};
