export default {
  'admin.devices.modalHeaderAdd': 'pleaseTranslate Add device',
  'admin.devices.twoWayMeter': 'pleaseTranslate Two way meter',
  'admin.devices.twoWayMeterUsed': 'pleaseTranslate Two way meter used',
  'admin.devices.primaryEnergy': 'pleaseTranslate Primary energy',
  'admin.devices.commissioning': 'pleaseTranslate Commissioning',
  'admin.devices.law': 'pleaseTranslate Law',
  'admin.devices.manufacturer': 'pleaseTranslate Manufacturer',
  'admin.devices.kwPeak': 'pleaseTranslate kW peak',
  'admin.devices.kwhPerAnnum': 'pleaseTranslate kWh per annum',
  'admin.devices.addNew': 'pleaseTranslate Add new device',
  'admin.devices.tablePrimaryEnergy': 'pleaseTranslate Primary energy',
  'admin.devices.tableManufacturer': 'pleaseTranslate Manufacturer',
  'admin.devices.tableStatus': 'pleaseTranslate Status',
  'admin.devices.tableKwPeak': 'pleaseTranslate kW peak',
  'admin.devices.tableLaw': 'pleaseTranslate Law',
  'admin.devices.tableCommissioning': 'pleaseTranslate Commissioning',
  'admin.devices.yes': 'pleaseTranslate Yes',
  'admin.devices.planned': 'pleaseTranslate Planned',
  'admin.devices.bio_mass': 'pleaseTranslate Bio mass',
  'admin.devices.bio_gas': 'pleaseTranslate Bio gas',
  'admin.devices.natural_gas': 'pleaseTranslate Natural gas',
  'admin.devices.fluid_gas': 'pleaseTranslate Fluid gas',
  'admin.devices.fuel_oil': 'pleaseTranslate Fuel oil',
  'admin.devices.wood': 'pleaseTranslate Wood',
  'admin.devices.veg_oil': 'pleaseTranslate Veg oil',
  'admin.devices.sun': 'pleaseTranslate Sun',
  'admin.devices.wind': 'pleaseTranslate Wind',
  'admin.devices.water': 'pleaseTranslate Water',
  'admin.devices.other': 'pleaseTranslate Other',
  'admin.devices.eeg': 'pleaseTranslate EEG',
  'admin.devices.kwkg': 'pleaseTranslate KWKG',
  'admin.devices.free': 'pleaseTranslate Free',
  'admin.devices.electricitySupplier.id': 'pleaseTranslate Electricity supplier',
  'admin.devices.headerDeviceDetails': 'pleaseTranslate Device details',
};
