export default {
  'admin.groups.tableName': 'Gruppenname',
  'admin.groups.tableEnergyType': 'Quelle',
  'admin.groups.headerSettings': 'Einstellungen',
  'admin.groups.headerGroup': 'Energiegruppe',
  'admin.groups.name': 'Gruppenname',
  'admin.groups.energySources': 'Quellen',
  'admin.groups.startDate': 'Starttermin',
  'admin.addresses.address': 'Adresse',
  'admin.groups.headerGroupsList': 'Deine Energiegruppen',
  'admin.groups.breadcrumbsMyLocalpools': 'My groups',
  'admin.groups.distributionSystemOperator': 'VNB',
  'admin.groups.transmissionSystemOperator': 'ÜNB',
  'admin.groups.electricitySupplier': 'Lieferant',
};
