export default {
  'admin.marketLocations.navConsumption': 'Bezugszähler',
  'admin.marketLocations.navProduction': 'Produktionszähler',
  'admin.marketLocations.navSystem': 'Systemzähler',
  'admin.marketLocations.navContracts': 'Verträge',
  'admin.marketLocations.navRegisters': 'Zählwerke',
  'admin.marketLocations.navAllMeters': 'Alle Zähler',
  'admin.marketLocations.tableName': 'Name',
  'admin.marketLocations.name': 'Bezugsstelle',
  'admin.marketLocations.thirdPartyId': 'MaLo ID',
  'admin.marketLocations.consumption': 'Verbrauch',
  'admin.marketLocations.production': 'Produktion',
  'admin.marketLocations.kind': 'MaLo Art',
  'admin.marketLocations.headerMarketLocationDetails': 'MaLo Details',
};
