export default {
  'admin.meters.reference': 'Vertragsreferenz',
  'admin.meters.productSerialnumber': 'Zählernummer',
  'admin.meters.manufacturerName': 'Herstellername',
  'admin.meters.easy_meter': 'EasyMeter',
  'admin.meters.amperix': 'Amperix',
  'admin.meters.ferraris': 'Ferraris',
  'admin.meters.other': 'Sonstiges',
  'admin.meters.productName': 'Produktname',
  'admin.meters.ownership': 'Besitzstatus',
  'admin.meters.BUZZN_SYSTEMS': 'BUZZN',
  'admin.meters.FOREIGN_OWNERSHIP': 'Fremdbesitz',
  'admin.meters.CUSTOMER': 'Kunde',
  'admin.meters.LEASED': 'Geleast',
  'admin.meters.BOUGHT': 'Gekauft',
  'admin.meters.edifactMeteringType': 'Zählertyp',
  'admin.meters.AHZ': 'analoger Haushaltszähler (Drehstrom)',
  'admin.meters.WSZ': 'analoger Wechselstromzähler',
  'admin.meters.LAZ': 'Lastgangzähler',
  'admin.meters.MAZ': 'Maximumzähler',
  'admin.meters.EHZ': 'elektronischer Haushaltszähler',
  'admin.meters.IVA': 'Individuelle Abstimmung (Sonderausstattung)',
  'admin.meters.edifactMeterSize': 'Größe',
  'admin.meters.Z01': 'EDL40',
  'admin.meters.Z02': 'EDL21',
  'admin.meters.Z03': 'sonstiger EHZ',
  'admin.meters.type': 'Typ',
  'admin.meters.meter_real': 'Echt',
  'admin.meters.meter_virtual': 'Virtuell',
  'admin.meters.directionNumber': 'Energierichtung',
  'admin.meters.ERZ': 'Einrichtungszähler',
  'admin.meters.ZRZ': 'Zweirichtungszähler',
  'admin.meters.section': 'Energie',
  'admin.meters.S': 'Strom',
  'admin.meters.G': 'Gas',
  'admin.meters.buildYear': 'Baujahr',
  'admin.meters.calibratedUntil': 'Geeicht bis',
  'admin.meters.sentDataDso': 'Daten an VNB versandt am',
  'admin.meters.edifactTariff': 'Tarifanzahl',
  'admin.meters.ETZ': 'Eintarif',
  'admin.meters.ZTZ': 'Zweitarif',
  'admin.meters.NTZ': 'Mehrtarif',
  'admin.meters.edifactMountingMethod': 'Befestigungsart',
  'admin.meters.DPA': 'Dreipunktaufhängung',
  'admin.meters.HS': 'Hutschiene',
  'admin.meters.BKE': 'Stecktechnik',
  'admin.meters.edifactMeasurementMethod': 'Ausleseart',
  'admin.meters.AMR': 'fernauslesbare Zähler',
  'admin.meters.MMR': 'manuell ausgelesene Zähler',
  'admin.meters.edifactVoltageLevel': 'Entnahmebene',
  'admin.meters.E03': 'Höchstspannung',
  'admin.meters.E04': 'Hochspannung',
  'admin.meters.E05': 'Mittelspannung',
  'admin.meters.E06': 'Niederspannung',
  'admin.meters.edifactCycleInterval': 'Turnusintervall',
  'admin.meters.MONTHLY': 'Monat',
  'admin.meters.YEARLY': 'Jahr',
  'admin.meters.QUARTERLY': 'Quartal',
  'admin.meters.HALF_YEARLY': 'Halbjahr',
  'admin.meters.edifactDataLogging': 'Datenerfassung',
  'admin.meters.Z04': 'analog',
  'admin.meters.Z05': 'elektronisch',
  'admin.meters.converterConstant': 'Wandlerfaktor',
  'admin.meters.headerMeterData': 'Zählpunkt',
  'admin.meters.headerClassification': 'Klassifizierung',
  'admin.meters.tableProductSerialnumber': 'Zählernummer',
  'admin.meters.headerRegistersReadings': 'Register und letzter Messwert',
  'admin.meters.headerMeterDetails': 'Zähler Details',
  'admin.meters.manufacturerDescription': 'Herstellerbeschreibung',
  'admin.meters.locationDescription': 'Installationsort',
  'admin.meters.dataSource': 'Datenquelle',
  'admin.meters.discovergy': 'Discovergy',
  'admin.meters.standard_profile': 'Standardlastprofil',
  'admin.meters.sequenceNumber': 'Laufende Nummer',
  'admin.meters.headerEdifactInformation': 'EDIFACT',
  'admin.meters.addNew': 'Neuen Zähler hinzufügen',
  'admin.registers.marketLocationId': 'MaLo ID',
  'admin.meters.meteringLocationId': 'MeLo ID',
  'admin.meters.real': 'Real',
  'admin.meters.virtual': 'Virtuell',
  'admin.meters.datasource': 'Datenquelle',
  'admin.meters.BUZZN': 'BUZZN',
  'admin.meters.updateDiscovergyMeter': 'Update Discovergy Zähler',
};
