export default {
  'admin.persons.phone': 'Telefon',
  'admin.persons.fax': 'Fax',
  'admin.persons.email': 'Email',
  'admin.persons.lastLogin': 'Letzter Login',
  'admin.persons.headerContact': 'Kontaktperson',
  'admin.persons.headerLegalRepresentation': '?? please, translate',
  'admin.persons.prefix': 'Anrede',
  'admin.persons.title': 'Titel',
  'admin.persons.firstName': 'Vorname',
  'admin.persons.lastName': 'Nachname',
  'admin.persons.mandateReference': 'SEPA Mandat',
  'admin.persons.F': 'Frau',
  'admin.persons.M': 'Herr',
  'admin.persons.Dr.': 'Dr.',
  'admin.persons.Prof.': 'Prof.',
  'admin.persons.Prof. Dr': 'Prof.Dr.',
  'admin.persons.headerMyProfile': 'My Profile',
  'admin.persons.headerBankAccounts': 'Bankkonten',
  'admin.persons.descriptionBankAccounts': 'Rechnungskonten',
  'admin.persons.navPillContactInfo': 'Kontaktdaten',
  'admin.persons.navPillAccount': 'Benutzerkonto',
  'admin.persons.navPillBank': 'Bankkonten',
  'admin.persons.customerNumber': 'Kundennummer',
};
