export default {
  'admin.readings.date': 'Ablesezeitpunkt',
  'admin.readings.wattHour': 'Wattstunde',
  'admin.readings.rawValue': 'Abgelesener Wert',
  'admin.readings.value': 'Wert',
  'admin.readings.unit': 'Einheit',
  'admin.readings.reason': 'Ablesegrund',
  'admin.readings.readBy': 'Ableser',
  'admin.readings.quality': 'Qualität',
  'admin.readings.source': 'Quelle',
  'admin.readings.status': 'Status',
  'admin.readings.comment': 'Kommentar',
  'admin.readings.Wh': 'Wh',
  'admin.readings.W': 'W',
  'admin.readings.m³': 'm³',
  'admin.readings.IOM': 'Geräteeinbau',
  'admin.readings.COM1': 'Gerätewechsel 1',
  'admin.readings.COM2': 'Gerätewechsel 2',
  'admin.readings.ROM': 'Geräteausbau',
  'admin.readings.PMR': 'Turnusablesung',
  'admin.readings.COT': 'Zwischenablesung',
  'admin.readings.COS': 'Vertragswechsel',
  'admin.readings.CMP': 'Geräteparameteränderung',
  'admin.readings.COB': 'Bilanzierungsgebietswechsel',
  'admin.readings.BN': 'Buzzn',
  'admin.readings.SN': 'Stromnehmer',
  'admin.readings.SG': 'Stromgeber',
  'admin.readings.VNB': 'Verteilnetzbetreiber',
  'admin.readings.20': 'Nicht verwendbarer Wert',
  'admin.readings.67': 'Ersatzwert (geschätzt)',
  'admin.readings.79': 'Energiemenge summiert',
  'admin.readings.187': 'Prognosewert',
  'admin.readings.220': 'Abgelesener Wert',
  'admin.readings.201': 'Vorschlagswert',
  'admin.readings.SM': 'SmartMeter',
  'admin.readings.MAN': 'Manual',
  'admin.readings.Z83': 'Z83 - Kundenselbstablesung',
  'admin.readings.Z84': 'Z84 - Leerstand',
  'admin.readings.Z86': 'Z86 - Plausibel wg. Kontrollablesung',
  'admin.readings.headerReading': 'Zählerstand',
  'admin.readings.tableDate': 'Datum',
  'admin.readings.tableValue': 'Messwert',
  'admin.readings.tableReason': 'Ablesegrund',
  'admin.readings.addNew': 'Messwert hinzufügen',
  'admin.readings.modalHeaderAdd': 'Messwert hinzufügen',
  'admin.readings.calculateReading': 'Messwert generieren'
};
