export default {
  'admin.registers.meteringPointId': 'Zählpunkt-Id',
  'admin.registers.type': 'Typ',
  'admin.registers.register_real': 'Echt',
  'admin.registers.register_virtual': 'Virtuell',
  'admin.registers.name': 'Name',
  'admin.registers.label': 'Kennzeichnung',
  'admin.registers.DEMARCATION_PV': 'Abgrenzung PV',
  'admin.registers.DEMARCATION_CHP': 'Abgrenzung BHKW',
  'admin.registers.PRODUCTION_PV': 'Produktion PV',
  'admin.registers.PRODUCTION_CHP': 'Produktion BHKW',
  'admin.registers.GRID_CONSUMPTION': 'Netz Verbrauch',
  'admin.registers.GRID_FEEDING': 'Netz Einspeisung',
  'admin.registers.GRID_CONSUMPTION_CORRECTED': 'Netz Verbrauch korrigiert',
  'admin.registers.GRID_FEEDING_CORRECTED': 'Netz Einspeisung korrigiert',
  'admin.registers.OTHER': 'Sonstiges',
  'admin.registers.CONSUMPTION': 'Verbrauch',
  'admin.registers.direction': 'Richtung',
  'admin.registers.in': 'Einspeisung',
  'admin.registers.out': 'Entnahme',
  'admin.registers.obis': 'OBIS',
  'admin.registers.preDecimalPosition': 'Vorkommastellen',
  'admin.registers.postDecimalPosition': 'Nachkommestellen',
  'admin.registers.lowLoadAbility': 'Schwachlastfähig',
  'admin.registers.observerEnabled': 'Überwachung eingeschaltet',
  'admin.registers.observerMinThreshold': 'Untere Schwelle',
  'admin.registers.observerMaxThreshold': 'Obere Schwelle',
  'admin.registers.observerOfflineMonitoring': 'Ausfallnachricht',
  'admin.registers.lastObserved': 'Letzte Überwachung am',
  'admin.registers.headerRegisterData': 'Zählwerk',
  'admin.registers.headerObservation': 'Überwachung',
  'admin.registers.navPillRegisterData': 'Zählwerk',
  'admin.registers.navPillFormula': 'Formel',
};
