export default {
  'admin.register_metas.name': 'pleaseTranslate Name',
  'admin.register_metas.label': 'pleaseTranslate Label',
  'admin.register_metas.DEMARCATION_PV': 'PV Abgrenzung',
  'admin.register_metas.DEMARCATION_CHP': 'BHKW Abgrenzung',
  'admin.register_metas.DEMARCATION_WATER': 'Wasser Abgrenzung',
  'admin.register_metas.DEMARCATION_WIND': 'Wind Abgrenzung',
  'admin.register_metas.PRODUCTION_PV': 'PV Produktion',
  'admin.register_metas.PRODUCTION_CHP': 'BHKW Produktion',
  'admin.register_metas.PRODUCTION_WATER': 'Wasser Produktion',
  'admin.register_metas.PRODUCTION_WIND': 'Wind Produktion',
  'admin.register_metas.GRID_CONSUMPTION': 'ÜGZ Bezug',
  'admin.register_metas.GRID_FEEDING': 'ÜGZ Einspeisung',
  'admin.register_metas.GRID_CONSUMPTION_CORRECTED': 'ÜGZ Bezug (korrigiert)',
  'admin.register_metas.GRID_FEEDING_CORRECTED': 'ÜGZ Einspeisung (korrigiert)',
  'admin.register_metas.OTHER': 'Sonstiges',
  'admin.register_metas.CONSUMPTION': 'Bezug',
  'admin.register_metas.CONSUMPTION_COMMON': 'Bezug - Allgemeinstrom',
};
