export default {
  'admin.registers.meteringPointId': 'Zählpunkt-Id',
  'admin.registers.type': 'Typ',
  'admin.registers.register_real': 'Echt',
  'admin.registers.register_virtual': 'Virtuell',
  'admin.registers.name': 'Name',
  'admin.registers.label': 'Kennzeichnung',
  'admin.registers.DEMARCATION_PV': 'PV Abgrenzung',
  'admin.registers.DEMARCATION_CHP': 'BHKW Abgrenzung',
  'admin.registers.DEMARCATION_WATER': 'Wasser Abgrenzung',
  'admin.registers.DEMARCATION_WIND': 'Wind Abgrenzung',
  'admin.registers.PRODUCTION_PV': 'PV Produktion',
  'admin.registers.PRODUCTION_CHP': 'BHKW Produktion',
  'admin.registers.PRODUCTION_WATER': 'Wasser Produktion',
  'admin.registers.PRODUCTION_WIND': 'Wind Produktion',
  'admin.registers.GRID_CONSUMPTION': 'ÜGZ Bezug',
  'admin.registers.GRID_FEEDING': 'ÜGZ Einspeisung',
  'admin.registers.GRID_CONSUMPTION_CORRECTED': 'ÜGZ Bezug (korrigiert)',
  'admin.registers.GRID_FEEDING_CORRECTED': 'ÜGZ Einspeisung (korrigiert)',
  'admin.registers.OTHER': 'Sonstiges',
  'admin.registers.CONSUMPTION': 'Bezug',
  'admin.registers.CONSUMPTION_COMMON': 'Bezug - Allgemeinstrom',
  'admin.registers.direction': 'Richtung',
  'admin.registers.in': 'Einspeisung',
  'admin.registers.out': 'Entnahme',
  'admin.registers.obis': 'OBIS',
  'admin.registers.preDecimalPosition': 'Vorkommastellen',
  'admin.registers.postDecimalPosition': 'Nachkommastellen',
  'admin.registers.lowLoadAbility': 'Schwachlastfähig',
  'admin.registers.observerEnabled': 'Überwachung eingeschaltet',
  'admin.registers.observerMinThreshold': 'Untere Schwelle',
  'admin.registers.observerMaxThreshold': 'Obere Schwelle',
  'admin.registers.observerOfflineMonitoring': 'Ausfallnachricht',
  'admin.registers.lastObserved': 'Letzte Überwachung am',
  'admin.registers.headerRegisterData': 'Zählwerk',
  'admin.registers.headerObservation': 'Überwachung',
  'admin.registers.navPillRegisterData': 'Zählwerk',
  'admin.registers.navPillReadings': 'Zählerstände',
  'admin.registers.navPillFormula': 'Formel',
  'admin.registers.tableName': 'Name',
  'admin.registers.tableDirection': 'Richtung',
  'admin.registers.tableLabel': 'Label',
  'admin.registers.headerRegisterPower': 'Aktueller Wert',
  'admin.registers.headerRegisterDetails': 'Zählwerk',
  'admin.registers.sharePublicly': 'Öffentlich teilen',
  'admin.registers.shareGroup': 'In der Gruppe teilen',
  'admin.registers.headerEdifactInformation': 'EDIFACT',
};
