export default {
  'admin.tariffs.pricing': 'Preis',
  'admin.tariffs.name': 'Tarif',
  'admin.tariffs.beginDate': 'Beginnt am',
  'admin.tariffs.endDate': 'Endet am',
  'admin.tariffs.energyPricePerKw': 'Preis pro kWh',
  'admin.tariffs.nbasePricePerMonth': 'Grundpreis pro Monat',
  'admin.tariffs.headerTariffData': 'Tarifdaten',
  'admin.tariffs.backTariffs': 'Stromtarif',
  'admin.tariffs.navActiveTariffs': 'Aktuelle Tarife',
  'admin.tariffs.navPastTariffs': 'Alte Tarife',
  'admin.tariffs.tableName': 'Name',
  'admin.tariffs.tableBeginDate': 'Starttermin',
  'admin.tariffs.tableEndDate': 'Endtermin',
  'admin.tariffs.tableLastDate': 'Enddatum',
  'admin.tariffs.tableBasepriceCentsPerMonth': 'netto Grundpreis/Monat',
  'admin.tariffs.tableEnergypriceCentsPerKwh': 'netto Arbeitspreis/kWh',
  'admin.tariffs.numberOfContracts': 'Verträge',
  'admin.tariffs.energypriceCentsPerKwh': 'Arbeitspreis/kWh',
  'admin.tariffs.basepriceCentsPerMonth': 'Grundpreis/Monat',
  'admin.tariffs.addNew': 'Tarif hinzufügen',
  'admin.tariffs.modalHeaderAdd': 'Tarif hinzufügen',
};
