export default {
  'en-US': {
    'admin.meters.productSerialnumber': 'Serial number:',
    'admin.meters.manufacturerName': 'Manufacturer name:',
    'admin.meters.productName': 'Product name:',
    'admin.meters.ownership': 'Ownership',
    'admin.meters.BUZZN_SYSTEMS': 'Buzzn Systems',
    'admin.meters.FOREIGN_OWNERSHIP': 'Foreign Ownership',
    'admin.meters.CUSTOMER': 'Customer',
    'admin.meters.LEASED': 'Leased',
    'admin.meters.BOUGHT': 'Bought',
    'admin.meters.edifactMeteringType': 'Meter type',
    'admin.meters.AHZ': 'analoger Haushaltszähler (Drehstrom)',
    'admin.meters.WSZ': 'analoger Wechselstromzähler',
    'admin.meters.LAZ': 'Lastgangzähler',
    'admin.meters.MAZ': 'Maximumzähler',
    'admin.meters.EHZ': 'elektronischer Haushaltszähler',
    'admin.meters.IVA': 'Individuelle Abstimmung (Sonderausstattung)',
    'admin.meters.edifactMeterSize': 'Meter size:',
    'admin.meters.Z01': 'EDL40',
    'admin.meters.Z02': 'EDL21',
    'admin.meters.Z03': 'Other',
    'admin.meters.type': 'Type',
    'admin.meters.meter_real': 'Real',
    'admin.meters.meter_virtual': 'Virtual',
    'admin.meters.directionNumber': 'Energy direction',
    'admin.meters.ERZ': 'Einrichtungszähler',
    'admin.meters.ZRZ': 'Zweirichtungszähler',
    'admin.meters.section': 'Energy',
    'admin.meters.S': 'Power',
    'admin.meters.G': 'Gas',
    'admin.meters.buildYear': 'Manufactured in',
    'admin.meters.calibratedUntil': 'Calibrated until',
    'admin.meters.sentDataDso': 'Sent data to DSO on',
    'admin.meters.edifactTariff': 'Number of Tariffs',
    'admin.meters.ETZ': 'Single tariff',
    'admin.meters.ZTZ': 'Dual tariff',
    'admin.meters.NTZ': 'Multi tariff',
    'admin.meters.edifactMountingMethod': 'Mounting',
    'admin.meters.DPA': 'Three point mounting',
    'admin.meters.HS': 'Cap rail',
    'admin.meters.BKE': 'Plug technique',
    'admin.meters.edifactMeasurementMethod': 'Measurement',
    'admin.meters.AMR': 'fernauslesbare Zähler',
    'admin.meters.MMR': 'manuell ausgelesene Zähler',
    'admin.meters.edifactVoltageLevel': 'Voltage Level',
    'admin.meters.E03': 'Highest voltage',
    'admin.meters.E04': 'High voltage',
    'admin.meters.E05': 'Medium voltage',
    'admin.meters.E06': 'Low voltage',
    'admin.meters.edifactCycleInterval': 'Cycle Interval',
    'admin.meters.MONTHLY': 'Month',
    'admin.meters.YEARLY': 'Year',
    'admin.meters.QUARTERLY': 'Quarter',
    'admin.meters.HALF_YEARLY': 'Half-year',
    'admin.meters.edifactDataLogging': 'Data logging',
    'admin.meters.Z04': 'analog',
    'admin.meters.Z05': 'electronic',
    'admin.meters.converterConstant': '40',
  },
};
