export default {
  'en-US': {
    'admin.meters.productSerialnumber': 'Serial number',
    'admin.meters.manufacturerName': 'Manufacturer name',
    'admin.meters.easy_meter': 'EasyMeter',
    'admin.meters.amperix': 'Amperix',
    'admin.meters.ferraris': 'Ferraris',
    'admin.meters.other': 'Other',
    'admin.meters.productName': 'Product name',
    'admin.meters.ownership': 'Ownership',
    'admin.meters.BUZZN_SYSTEMS': 'Buzzn Systems',
    'admin.meters.FOREIGN_OWNERSHIP': 'Foreign Ownership',
    'admin.meters.CUSTOMER': 'Customer',
    'admin.meters.LEASED': 'Leased',
    'admin.meters.BOUGHT': 'Bought',
    'admin.meters.edifactMeteringType': 'Meter type',
    'admin.meters.AHZ': 'analog household meter',
    'admin.meters.WSZ': 'analog AC meter',
    'admin.meters.LAZ': 'Load profile meter',
    'admin.meters.MAZ': 'maximum meter',
    'admin.meters.EHZ': 'electronic household meter',
    'admin.meters.IVA': 'individual reconciliation',
    'admin.meters.edifactMeterSize': 'Meter size',
    'admin.meters.Z01': 'EDL40',
    'admin.meters.Z02': 'EDL21',
    'admin.meters.Z03': 'Other',
    'admin.meters.type': 'Type',
    'admin.meters.meter_real': 'Real',
    'admin.meters.meter_virtual': 'Virtual',
    'admin.meters.directionNumber': 'Energy direction',
    'admin.meters.ERZ': 'One-Way Meter',
    'admin.meters.ZRZ': 'Two-Way Meter',
    'admin.meters.section': 'Energy',
    'admin.meters.S': 'Power',
    'admin.meters.G': 'Gas',
    'admin.meters.buildYear': 'Manufactured in',
    'admin.meters.calibratedUntil': 'Calibrated until',
    'admin.meters.sentDataDso': 'Sent data to DSO on',
    'admin.meters.edifactTariff': 'Number of Tariffs',
    'admin.meters.ETZ': 'Single tariff',
    'admin.meters.ZTZ': 'Dual tariff',
    'admin.meters.NTZ': 'Multi tariff',
    'admin.meters.edifactMountingMethod': 'Mounting',
    'admin.meters.DPA': 'Three point mounting',
    'admin.meters.HS': 'Cap rail',
    'admin.meters.BKE': 'Plug technique',
    'admin.meters.edifactMeasurementMethod': 'Measurement',
    'admin.meters.AMR': 'fernauslesbare Zähler',
    'admin.meters.MMR': 'manuell ausgelesene Zähler',
    'admin.meters.edifactVoltageLevel': 'Voltage Level',
    'admin.meters.E03': 'Highest voltage',
    'admin.meters.E04': 'High voltage',
    'admin.meters.E05': 'Medium voltage',
    'admin.meters.E06': 'Low voltage',
    'admin.meters.edifactCycleInterval': 'Cycle Interval',
    'admin.meters.MONTHLY': 'Month',
    'admin.meters.YEARLY': 'Year',
    'admin.meters.QUARTERLY': 'Quarter',
    'admin.meters.HALF_YEARLY': 'Half-year',
    'admin.meters.edifactDataLogging': 'Data logging',
    'admin.meters.Z04': 'analog',
    'admin.meters.Z05': 'electronic',
    'admin.meters.converterConstant': 'Converter Constant',
    'admin.meters.headerMeterData': 'Meter Data',
    'admin.meters.headerClassification': 'Classification',
    'admin.registers.meteringPointId': 'Metering Point Id',
    'admin.registers.type': 'Type',
    'admin.registers.register_real': 'Real',
    'admin.registers.register_virtual': 'Virtual',
    'admin.registers.name': 'Name',
    'admin.registers.label': 'Label',
    'admin.registers.DEMARCATION_PV': 'Demarcation PV',
    'admin.registers.DEMARCATION_CHP': 'Demarcation CHP',
    'admin.registers.PRODUCTION_PV': 'Production PV',
    'admin.registers.PRODUCTION_CHP': 'Produktion CHP',
    'admin.registers.GRID_CONSUMPTION': 'Grid consumption',
    'admin.registers.GRID_FEEDING': 'Grid Feed-in',
    'admin.registers.GRID_CONSUMPTION_CORRECTED': 'Grid consumption corrected',
    'admin.registers.GRID_FEEDING_CORRECTED': 'Grid Feed-in korrigiert',
    'admin.registers.OTHER': 'Other',
    'admin.registers.CONSUMPTION': 'Consumption',
    'admin.registers.direction': 'Direction',
    'admin.registers.in': 'Feed-In',
    'admin.registers.out': 'Draw',
    'admin.registers.obis': 'OBIS',
    'admin.registers.preDecimalPosition': 'Pre-decimal position',
    'admin.registers.postDecimalPosition': 'Post-decimal position',
    'admin.registers.lowLoadAbility': 'Low load ability',
    'admin.registers.observerEnabled': 'Observation enabled',
    'admin.registers.observerMinThreshold': 'Minimum threshold',
    'admin.registers.observerMaxThreshold': 'Maximum threshold',
    'admin.registers.observerOfflineMonitoring': 'Offline alert',
    'admin.registers.lastObserved': 'Last observation on',
    'admin.registers.headerRegisterData': 'Register Data',
    'admin.registers.headerObservation': 'Observation',
    'admin.registers.navPillRegisterData': 'Register Data',
    'admin.registers.navPillReadings': 'Readings',
    'admin.registers.navPillFormula': 'Formula',
  },
};
